<!doctype html>
<html lang="ru">

<body>
  <?php
    $host = 'localhost';  // Хост, у нас все локально
    $user = 'mysql';    // Имя созданного вами пользователя
    $pass = 'mysql'; // Установленный вами пароль пользователю
    $db_name = 'rbtex';   // Имя базы данных
    $link = mysqli_connect($host, $user, $pass, $db_name); // Соединяемся с базой

    // Ругаемся, если соединение установить не удалось
    if (!$link) {
      echo 'Не могу соединиться с БД. Код ошибки: ' . mysqli_connect_errno() . ', ошибка: ' . mysqli_connect_error();
      exit;
    }
  ?>
</body>
</html>


<?php
  //Если переменная fam передана
  if (isset($_POST["fam"])) {
    //Вставляем данные, подставляя их в запрос
    $sql = mysqli_query($link, "INSERT INTO `klient` (`fam`, `name`, `phone`) VALUES ('{$_POST['fam']}','{$_POST['name']}', '{$_POST['phone']}')");
    
  }
?>
<!DOCTYPE html><html prefix="og: http://ogp.me/ns#" dir="ltr" lang="ru"><head>
	
    <meta charset="UTF-8">
	

	<title>Ремонт бытовой техники | Сервисный центр "Надежда"</title>
	<meta name="description" content="СЦ «НАДЕЖДА»: Вызов МАСТЕРА по ремонту на дом в Ачинске! Выезд и диагностика - БЕСПЛАТНО в день звонка! ГАРАНТИЯ - 1 ГОД. Телефон 8 923 333-33-33. Звоните!">
	
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="yandex-verification" content="67bfc2aa9b29e3df">
	<meta name="facebook-domain-verification" content="rb3486fhlvp82dksc22xxxy14cu1zs">

	<!-- Template Basic Images Start -->
	<meta property="og:type" content="website">
	<meta property="og:title" content="Ремонт бытовой техники - Сервисный центр " Надежда"">
	<meta property="og:description" content="СЦ «НАДЕЖДА»: Вызов МАСТЕРА по ремонту на дом в Ачинске! Выезд и диагностика - БЕСПЛАТНО в день звонка! ГАРАНТИЯ - 1 ГОД. Телефон 8 923 354-17-40. Звоните!">
	<meta property="og:image" content="images/logo_cr.png">
	<meta property="og:url" content="https://xn--80aapjcqhdedclqhfqo8b7c0ct.xn--p1ai/master-na-dom">
	<link rel="canonical" href="https://стиральныхмашинремонт.рф/master-na-dom">
	<link rel="icon" href="images/f-icon.png">
	<link rel="apple-touch-icon" sizes="180x180" href="images/f-icon.png">
	<!-- Template Basic Images End -->
	
	<!-- Custom Browsers Color Start -->
	<meta name="theme-color" content="#000">
	<!-- Custom Browsers Color End -->
	
	<link rel="stylesheet" href="css/magnific-popup.min.css">
	<link rel="stylesheet" href="css/slick.css">
	<link rel="stylesheet" href="css/main.min.css">

	<script type="text/javascript" async src="index.php"></script><script async src="https://cdn.bitrix24.ru/b1505153/crm/site_button/loader_16_ty31o9.js?27510731"></script><script async src="js/tag.js"></script><script>(function(w, c){(w[c]=w[c]||[]).push(function(){new zTracker({"id":"5bc3a797b1031b74d96bf70650a5683210245","metrics":{"metrika":"26280084","ga":"UA-104919178-4"}});});})(window, "zTrackerCallbacks");</script>
<script async id="zd_ct_phone_script" src="js/ct_phone.min.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
   m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

   ym(26280084, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true,
        webvisor:true
   });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/26280084" style="position:absolute; left:-9999px;" alt></div></noscript>
<!-- /Yandex.Metrika counter -->

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-104919178-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-104919178-4');
</script>

<script type="text/javascript">!function(){var t=document.createElement("script");t.type="text/javascript",t.async=!0,t.src="https://vk.com/js/api/openapi.js?169",t.onload=function(){VK.Retargeting.Init("VK-RTRG-984292-4UBhM"),VK.Retargeting.Hit()},document.head.appendChild(t)}();</script><script type="text/javascript" async src="https://vk.com/js/api/openapi.js?169"></script>
<noscript><img src="https://vk.com/rtrg?p=VK-RTRG-984292-4UBhM" style="position:fixed; left:-999px;" alt></noscript>


	
  </head>
  
  <body>
	
	<header class="header">
	  
	  <div class="container-fluid" id="js-fixed">
  <div class="container">
	<div class="row">
	  <div class="col">
		<div class="header__top-line">
		  <a href="http://localhost/test/index1.phtml" class="logo">
			<img class="img-responsive large" src="images/logo.png" alt="logo">
			<img class="img-responsive small" src="images/logo_cr.png" alt="logo">
		  </a>
		  
		  <nav class="nav hidden-md">
			<ul>
			  <li><a href="#advantages"></a></li>
			  <li><a href="#price"></a></li>
			  <li><a href="#steps"></a></li>
			  <li><a href="#about"></a></li>
			 
			  <li><a href="#contacts"></a></li>
<li><a href=index1.phtml>Выйти</a></li>
			</ul>
		  </nav>
		  
		  <div class="tel-box">
			8-933-333-33-33
			<p>г.Ачинск</p>
		  </div>
		  
		  <p class="visible-mb">
			
			<button class="btn btn-primary menu-button" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
			  <i class="icon-menu"></i>
			</button>
			
		  </p>
		  <div class="collapse" id="collapseExample">
			<nav class="nav collapse-nav">
			  <ul>
				<li><a href="#advantages"></a></li>
				<li><a href="#price"></a></li>
				<li><a href="#steps"></a></li>
				<li><a href="#about"></a></li>
				
				<li><a href="#contacts"></a></li>
			  </ul>
			</nav>
		  </div>
		  
		</div>
		
	  </div>
	</div>
  </div>
</div>
	  
	 

		
	  </div>
	</header>
	
	
	
	
	<section class="price" id="price">
	  <div class="container">
			<div class="row">
				<div class="col">
					<div class="heading">
						<h2 class="h2">Список клиентов</h2>
					</div>
						
					<ul class="price-box">
						<li class="price-box-lg">
							<table class="table table-striped">
								<thead class="t-heading">
									<tr>
										<th>Фамилия</th>
										<th>Имя</th>
										<th>Телеофн</th>
										
									</tr>
								</thead>


 <?php 
    $conn = mysqli_connect("localhost", "mysql", "mysql", "rbtex"); 
    // Check connection 
    if ($conn->connect_error) { 
    die("Connection failed: " . $conn->connect_error); 
    }  
    $sql = "SELECT fam, name, phone FROM klient"; 

    $result = $conn->query($sql); 
    if ($result->num_rows > 0) { 

      // output data of each row 
    while($row = $result->fetch_assoc()) { 

      echo "<tr><td>" . $row["fam"]
        . "</td><td>" . $row["name"] 
        . "</td><td>" . $row["phone"]
        . "</td></tr>"; 
    } 
    echo "</tbody>";

    } else { echo "0 results"; } 
    $conn->close(); 
  ?> 


								
							</table>
			  				
					</ul>
					

				</div>
			</div>
		</div>
	</section>

	

	

	
  
</body></html>