<!doctype html>
<html lang="ru">

<body>
  <?php
    $host = 'localhost';  // Хост, у нас все локально
    $user = 'mysql';    // Имя созданного вами пользователя
    $pass = 'mysql'; // Установленный вами пароль пользователю
    $db_name = 'rbtex';   // Имя базы данных
    $link = mysqli_connect($host, $user, $pass, $db_name); // Соединяемся с базой

    // Ругаемся, если соединение установить не удалось
    if (!$link) {
      echo 'Не могу соединиться с БД. Код ошибки: ' . mysqli_connect_errno() . ', ошибка: ' . mysqli_connect_error();
      exit;
    }
  ?>
</body>
</html>


<?php
  //Если переменная fam передана
  if (isset($_POST["fam"])) {
    //Вставляем данные, подставляя их в запрос
    $sql = mysqli_query($link, "INSERT INTO `klient` (`fam`, `name`, `phone`) VALUES ('{$_POST['fam']}','{$_POST['name']}', '{$_POST['phone']}')");
    
  }
?>
<!DOCTYPE html><html prefix="og: http://ogp.me/ns#" dir="ltr" lang="ru"><head>
	
    <meta charset="UTF-8">
	

	<title>Ремонт бытовой техники | Сервисный центр "Надежда"</title>
	<meta name="description" content="СЦ «НАДЕЖДА»: Вызов МАСТЕРА по ремонту на дом в Ачинске! Выезд и диагностика - БЕСПЛАТНО в день звонка! ГАРАНТИЯ - 1 ГОД. Телефон 8 923 333-33-33. Звоните!">
	
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="yandex-verification" content="67bfc2aa9b29e3df">
	<meta name="facebook-domain-verification" content="rb3486fhlvp82dksc22xxxy14cu1zs">

	<!-- Template Basic Images Start -->
	<meta property="og:type" content="website">
	<meta property="og:title" content="Ремонт бытовой техники - Сервисный центр " Надежда"">
	<meta property="og:description" content="СЦ «НАДЕЖДА»: Вызов МАСТЕРА по ремонту на дом в Ачинске! Выезд и диагностика - БЕСПЛАТНО в день звонка! ГАРАНТИЯ - 1 ГОД. Телефон 8 923 354-17-40. Звоните!">
	<meta property="og:image" content="images/logo_cr.png">
	<meta property="og:url" content="https://xn--80aapjcqhdedclqhfqo8b7c0ct.xn--p1ai/master-na-dom">
	<link rel="canonical" href="https://стиральныхмашинремонт.рф/master-na-dom">
	<link rel="icon" href="images/f-icon.png">
	<link rel="apple-touch-icon" sizes="180x180" href="images/f-icon.png">
	<!-- Template Basic Images End -->
	
	<!-- Custom Browsers Color Start -->
	<meta name="theme-color" content="#000">
	<!-- Custom Browsers Color End -->
	
	<link rel="stylesheet" href="css/magnific-popup.min.css">
	<link rel="stylesheet" href="css/slick.css">
	<link rel="stylesheet" href="css/main.min.css">

	<script type="text/javascript" async src="index.php"></script><script async src="https://cdn.bitrix24.ru/b1505153/crm/site_button/loader_16_ty31o9.js?27510731"></script><script async src="js/tag.js"></script><script>(function(w, c){(w[c]=w[c]||[]).push(function(){new zTracker({"id":"5bc3a797b1031b74d96bf70650a5683210245","metrics":{"metrika":"26280084","ga":"UA-104919178-4"}});});})(window, "zTrackerCallbacks");</script>
<script async id="zd_ct_phone_script" src="js/ct_phone.min.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
   m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

   ym(26280084, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true,
        webvisor:true
   });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/26280084" style="position:absolute; left:-9999px;" alt></div></noscript>
<!-- /Yandex.Metrika counter -->

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-104919178-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-104919178-4');
</script>

<script type="text/javascript">!function(){var t=document.createElement("script");t.type="text/javascript",t.async=!0,t.src="https://vk.com/js/api/openapi.js?169",t.onload=function(){VK.Retargeting.Init("VK-RTRG-984292-4UBhM"),VK.Retargeting.Hit()},document.head.appendChild(t)}();</script><script type="text/javascript" async src="https://vk.com/js/api/openapi.js?169"></script>
<noscript><img src="https://vk.com/rtrg?p=VK-RTRG-984292-4UBhM" style="position:fixed; left:-999px;" alt></noscript>


	
  </head>
  
  <body>
	
	<header class="header">
	  
	  <div class="container-fluid" id="js-fixed">
  <div class="container">
	<div class="row">
	  <div class="col">
		<div class="header__top-line">
		  <a href="http://localhost/test/index1.phtml" class="logo">
			<img class="img-responsive large" src="images/logo.png" alt="logo">
			<img class="img-responsive small" src="images/logo_cr.png" alt="logo">
		  </a>
		  
		  <nav class="nav hidden-md">
			<ul>
			  <li><a href="#advantages">Преимущества</a></li>
			  <li><a href="#price">Цены</a></li>
			  <li><a href="#steps">Как мы работаем</a></li>
			  <li><a href="#about">О компании</a></li>
			 
			  <li><a href="#contacts">Контакты</a></li>
<li><a href=vxod.phtml>Войти</a></li>
			</ul>
		  </nav>
		  
		  <div class="tel-box">
			8-933-333-33-33
			<p>г.Ачинск</p>
		  </div>
		  
		  <p class="visible-mb">
			
			<button class="btn btn-primary menu-button" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
			  <i class="icon-menu"></i>
			</button>
			
		  </p>
		  <div class="collapse" id="collapseExample">
			<nav class="nav collapse-nav">
			  <ul>
				<li><a href="#advantages">Преимущества</a></li>
				<li><a href="#price">Цены</a></li>
				<li><a href="#steps">Как мы работаем</a></li>
				<li><a href="#about">О компании</a></li>
				
				<li><a href="#contacts">Контакты</a></li>
			  </ul>
			</nav>
		  </div>
		  
		</div>
		
	  </div>
	</div>
  </div>
</div>
	  
	  <div class="header__main">
		
		<div class="container">
  <div class="row">
	<div class="col">
	  
	  <h1 class="h1"><span class="long">Нужен мастер по ремонту?</span></h1>
	  
	  <div class="heading-box">
		<ul class="icons-box">
		  <li><img src="images/medal1.png" alt="picture"></li>
		  <li><img src="images/medal2.png" alt="picture"></li>
		  <li><img src="images/medal3.png" alt="picture"></li>
		</ul>
		
		<div class="heading-text">
		  <div class="text-block">
			<p class="call">Звоните <span>или</span> Закажите звонок</p>
			<p class="today">Наш мастер придет к Вам на помощь уже сегодня! </p>
			<p class="phone phone1">8-933-333-33-33</p>
		  </div>
		  
		  <form id="form_1" class="form form-box" method="post"; return true;">
			
			<p class="form-heading">ОСТАВЬТЕ ЗАЯВКУ!<br>Мы перезвоним в течение 5 минут!</p>
			<!-- <p class="form-heading">ОСТАВЬТЕ ЗАЯВКУ НА РЕМОНТ!</p> -->

			<div class="form-control"method="post">
			  <div class="form-top">
				<div class="form-col">
				  <input type="text" class="form-control__item" name="fam" placeholder="Ваша фамилия" required>
				<input type="text" class="form-control__item" name="name" placeholder="Ваше имя" required>
  <input type="tel" class="form-control__item input-tel" name="problem" placeholder="Опишите проблему" required>
				  <input type="tel" class="form-control__item input-tel" name="phone" placeholder="Ваш телефон" required>
			  	  <p class="hint">Введите 10 цифр без первой "8"</p>
				</div>
				
			  </div>
			  <div class="form-bottom" method="post">
				<input class="hidden" type="text" name="userId" value>
				<!-- <input type="checkbox" id="agree" checked required/> -->
				<!-- <label for="agree">я согласен с политикой конфиденциальности</label> -->
			  </div>
			</div>
			<p class="form-text">Введите данные - нажмите кнопку <input type="submit" class="button dark-button" name="submit" value="ВЫЗВАТЬ МАСТЕРА"></p>
		  </form>
		  


		</div>
	  </div>
	</div>
  </div>
</div>


		
	  </div>
	</header>
	
	<section class="advantages" id="advantages">
	  <div class="container">
			<div class="row">
				<div class="col">
					<div class="heading">
						<h2 class="h2">Почему ВАМ с НАМИ выгоднее?</h2>
					</div>

					<ul class="advantages-box">
						<li class="box-column">
							<ul>
								<li class="advantages-item">
									<img src="images/adv11.png" alt="icon">
									<p>Ремонтируем бытовую технику<br>с 2022 года</p>
								</li>
								<li class="advantages-item">
									<img src="images/adv12.png" alt="icon">
									<p>Ремонтируем за ОДИН ВИЗИТ</p>
								</li>
								<li class="advantages-item">
									<img src="images/adv13.png" alt="icon">
									<p>ЛУЧШИЕ мастера в Ачинске</p>
								</li>
							</ul>
						</li>

						<li class="box-column empty-column">
							<!--<img src="/assets/templates/img/adv-pic.png" alt="picture">-->
						</li>

						<li class="box-column">
							<ul>
								<li class="advantages-item">
									<img src="images/adv21.png" alt="icon">
									<p>Даем ГАРАНТИЮ на все виды работ</p>
								</li>
								<li class="advantages-item">
									<img src="images/adv22.png" alt="icon">
									<p>ЧЕСТНАЯ цена по ПРАЙСУ</p>
								</li>
								<li class="advantages-item">
									<img src="images/adv23.png" alt="icon">
									<p>Собственный СКЛАД запчастей</p>
								</li>
							</ul>
						</li>
					</ul>
					
				</div>
			</div>
		</div>
	</section>

	<section class="repair" id="repair">
	  <div class="container">
	  <div class="row">
		<div class="col">
		  <div class="heading">
			<h2 class="h2">Ремонт ВСЕХ моделей и марок</h2>
		  </div>
		  
		  <ul class="repair-box">
			<li><a href="#price"><img class="img-responsive" src="images/r2.png" alt="ремонт indesit"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r8.png" alt="ремонт ariston"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r7.png" alt="ремонт lg"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r4.png" alt="ремонт samsung"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r11.png" alt="ремонт bosch"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r3.png" alt="ремонт liebherr"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r16.png" alt="ремонт electrolux"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r17.png" alt="ремонт whirpool"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r19.png" alt="ремонт siemens"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r1.png" alt="ремонт ardo"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r5.png" alt="ремонт aeg"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r9.png" alt="ремонт beko"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r10.png" alt="ремонт gorenje"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r12.png" alt="ремонт haier"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r15.png" alt="ремонт candy"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r18.png" alt="ремонт zanussi"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r23.png" alt="ремонт miele"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r24.png" alt="ремонт sharp"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r21.png" alt="ремонт атлант"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r6.png" alt="ремонт bauknecht"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r13.png" alt="ремонт asko"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r14.png" alt="ремонт kaiser"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r20.png" alt="ремонт smeg"></a></li>
			<li><a href="#price"><img class="img-responsive" src="images/r22.png" alt="ремонт vestfrost"></a></li>
		  </ul>
		</div>
	  </div>
	</div>
	</section>

	<section class="steps" id="steps">
	  <div class="container">
	  <div class="row">
		<div class="col">
		  
		  <div class="heading">
			<h2 class="h2">От вызова до ремонта ровно ОДИН шаг:</h2>
		  </div>
		  
		  <div class="steps-box">
			<ul class="steps-top">
			  <li><span>Звонок оператору</span><img src="images/step1.png" alt="icon"></li>
			  <li><span>Мастер едет на вызов</span><img src="images/step2.png" alt="icon"></li>
			  <li><span>Долгожданный ремонт</span><img src="images/step3.png" alt="icon"></li>
			</ul>
			<img class="img-responsive steps-line" src="images/steps-line.png" alt="pic">
			<ul class="steps-bottom">
			  <li>8 мин</li>
			  <li>20 мин</li>
			  <li>30 мин</li>
			  <li>60 мин</li>
			</ul>
		  </div>
		  
		</div>
	  </div>
	</div>
	</section>
	
	
	
	<section class="price" id="price">
	  <div class="container">
			<div class="row">
				<div class="col">
					<div class="heading">
						<h2 class="h2">Распространенные неисправности и примерная<br>стоимость работ по ремонту</h2>
					</div>
						<!-- <p style="font-size:16px;color:#223e81;">ВНИМАНИЕ! На текущий момент прайс-лист находится на пересмотре. Актуальную стоимость ремонта уточняйте у оператора по телефону.</p> -->
						<p style="font-size: 20px;color:#223e81;padding-top: 10px;">Для пенсионеров и многодетных семей действуют <b>СКИДКИ</b> до <b>15%</b> на стоимость ремонтных работ!</p>

					<ul class="price-box">
						<li class="price-box-lg">
							<table class="table table-striped">
								<thead class="t-heading">
									<tr>
										<th>Поломка</th>
										<th>Причина поломки</th>
										<th>Работы</th>
										<th>Стоимость</th>
									</tr>
								</thead>
								<tbody>
 									<tr>
										<td>Выезд мастера</td>
										<td></td>
										<td></td>
										<td>Бесплатно</td>
									</tr>
									<tr>
										<td>Диагностика (в случае ремонта)</td>
										<td></td>
										<td></td>
										<td>Бесплатно*</td>
									</tr> 
									<tr>
										<td rowspan="5">Не включается стиральная машинка</td>
										<td>Сломался управляющий модуль</td>
										<td>Ремонт или замена</td>
										<td>7000 руб</td>
									</tr>
									<tr>
										<td>Частичная или полная поломка УБЛ</td>
										<td rowspan="4">Замена или ремонт</td>
										<td>4000 руб</td>
									</tr>
									<tr>
										<td>Неисправна кнопка включения машинки</td>
										<td>2500 руб</td>
									</tr>
									<tr>
										<td>Повреждение внутренних проводов</td>
										<td>2000 руб</td>
									</tr>
									<tr>
										<td>Сбой в фильтре помех</td>
										<td>3000 руб</td>
									</tr>
									<tr>
										<td rowspan="3">Не греет воду</td>
										<td>Сбои в модуле управления</td>
										<td>Ремонт или замена</td>
										<td>7000 руб</td>
									</tr>
									<tr>
										<td>Вышел из строя ТЭН</td>
										<td rowspan="2">Замена или ремонт</td>
										<td>5000 руб</td>
									</tr>
									<tr>
										<td>Неисправен температурный датчик</td>
										<td>2500 руб</td>
									</tr>
									<tr>
										<td rowspan="4">Не крутит барабан</td>
										<td>Сбои в электронном модуле</td>
										<td>Ремонт или замена</td>
										<td>7000 руб</td>
									</tr>
									<tr>
										<td>Износ щеток электродвигателя</td>
										<td rowspan="2">Замена</td>
										<td>4500 руб</td>
									</tr>
									<tr>
										<td>Неисправен ремень привода</td>
										<td>3500 руб</td>
									</tr>
									<tr>
										<td>Вышел из строя электродвигатель</td>
										<td>Замена или ремонт</td>
										<td>7000 руб</td>
									</tr>
									<tr>
										<td rowspan="4">Ремонт телевизоров ЖК</td>
										<td>Перегорела матрица</td>
										<td rowspan="2">Замена</td>
										<td>5500 руб</td>
									</tr>
									<tr>
										<td>Сгорел светодиод</td>
										<td>5000 руб</td>
									</tr>
									<tr>
										<td>не идет питание</td>
										<td>замена кабеля</td>
										<td>1500 руб</td>
									</tr>
									<tr>
										<td>Разбит экран</td>
										<td>замена</td>
										<td>7500 руб</td>
									</tr>
									<tr>
										<td rowspan="5">Не холодит</td>
										<td>Утечка фреона</td>
										<td>замена</td>
										<td>1200 руб</td>
									</tr>
									<tr>
										<td>Терморегулятор</td>
										<td rowspan="2">Замена или ремонт</td>
										<td>1500 руб</td>
									</tr>
									<tr>
										<td>Реле</td>
										<td>1000 руб</td>
									</tr>
									<tr>
										<td rowspan="2">Капиллярная трубка</td>
										<td>Прочистка</td>
										<td>1500 руб</td>
									</tr>
									<tr>
										<td>Замена</td>
										<td>2500 руб</td>
									</tr>
									
								</tbody>
							</table>
			  				<p style="font-size:14px;">* При отказе от ремонта стоимость диагностики - 500 руб</p>
						
					</ul>
					<div class="text-box">
						<p class="text">ПОЗВОНИТЕ В НАШУ ДИСПЕТЧЕРСКУЮ СЛУЖБУ И ПРОКОНСУЛЬТИРУЙТЕСЬ О СТОИМОСТИ РЕМОНТА.<br>
ЭТО АБСОЛЮТНО БЕСПЛАТНО!</p>
					</div>

				</div>
			</div>
		</div>
	</section>

	

	<section class="about" id="about">
	  <div class="container">
			<div class="row">
				<div class="col">
					<div class="heading">
						<h2 class="h2">О компании</h2>
					</div>
		  <p>Сервисный центр "Надежда" является сертифицированным сервисным центром по ремонту бытовой техники и электроники, что подтверждается сертификатом соответствия, выданным Федеральным агентством по техническому регулированию и метрологии.</p>
		  <p>Этот сертификат регулярно подтверждается нашей компанией раз в три года, что является дополнительным доказательством нашего профессионализма и надежности.</p>

		  <ul class="repair-box sert-box hidden">
			<li><a href="/assets/templates/img/ogrn.jpg" class="image-popup"><img class="img-responsive" src="images/ogrn_sm.jpg" alt="Свидетельство ОГРН"></a></li>
			<li><a href="/assets/templates/img/inn.jpg" class="image-popup"><img class="img-responsive" src="images/inn_sm.jpg" alt="Свидетельство ИНН"></a></li>
			<li><a href="/assets/templates/img/sertifikat.jpg" class="image-popup"><img class="img-responsive" src="images/sertifikat_sm.jpg" alt="Сертификат СЦ Надежда"></a></li>
		  </ul>

					<p>Сервисный центр «Надежда» предлагает полный комплекс услуг по ремонту бытовой техники в Ачинске.</p>
					<p>Мы работаем:</p>
					<ul class="about-list">
						<li>ОПЕРАТИВНО. После звонка в нашу диспетчерскую службу мастер выезжает в течение нескольких часов.</li>
						<li>НАДЕЖНО. Надежность ремонта гарантируется фирменными проверенными запчастями и большим опытом работы наших мастеров.</li>
						<li>С БЕСПЛАТНЫМ ВЫЕЗДОМ В АЧИНСКЕ. Вы оплачиваете только ремонт или результативную диагностику. Нет результата - нет оплаты.</li>
						<li>С ГАРАНТИЕЙ. 6 месяцев гарантии на все работы и запчасти.</li>
					</ul>
					<p>Сломалась стиральная машина? Не работает телевизор? Заблокировался люк? Потекла вода? К сожалению, есть много причин, по которым бытовые приборы могут выйти из строя, но если вы сразу же обратитесь в наш сервисный центр по ремонту в Ачинске, все проблемы с вашей бытовой техникой будут решены в кратчайшие сроки. Мы осуществляем ремонт на дому.<br><br></p>
					<p>Мы производим следующие работы:</p>
					<ol>
						<li>Диагностика неисправности</li>
						<li>Ремонт или замена двигателя</li>
						<li>Замена помпы (сливного насоса)</li>
						<li>Ремонт телевизора</li>
						<li>Замена подсветки</li>
						<li>Ремонт, прошивка или замена электронного модуля (платы управления)</li>
					
						<li>Ремонт электропроводки</li>
					</ol>
					<p>и многое другое.<br><br></p>
					<p>После звонка в наш сервисный центр, мастер по ремонту выедет к вам на дом, произведет диагностику, оценит стоимость ремонта и быстро и аккуратно осуществит ремонт на дому если это возможно. Стаж работы мастеров нашего сервисного центра по ремонту превышает 10 лет. Ремонт осуществляется только с использованием проверенных фирменных запчастей. Мастер несет персональную ответственность за качество ремонта и заинтересован сделать его быстро и качественно. Все это гарантирует высочайший уровень ремонта.
					<br>Звонки принимает профессиональная диспетчерская служба, которая быстро и четко распределяет заявки по ближайшим свободным мастерам. Это гарантирует оперативность выезда мастера.</p>
					<p class="text">Звоните прямо сейчас в нашу диспетчерскую службу, оставляйте заявку на ремонт и больше не думайте ни о чем, все остальные заботы мы возьмем на себя.</p>

					
				</div>
			</div>
		</div>
	</section>
	
	
	
	
	

	<section class="contacts" id="contacts">
	  <div class="container">
	  
	  <div class="row">
		<div class="col">
		  <div class="heading">
			<h2 class="h2">Наши контакты</h2>
			<p>Сервисный центр "Надежда": <br>
			  ремонт бытовой техники.</p>
		  </div>
		</div>
	  </div>
	  
	  <div class="row d-flex">
		
		<div class="col-md-5">
		  <ul class="contacts__text d-flex flex-column justify-content-between align-content-between h-100">
			<li>
			  <p><i class="icon-phone"></i>Наш телефон:</p>
			  <p class="phone1 zphone">8-933-333-33-33</p>
			</li>
			<li>
			  <p><i class="icon-clock"></i>Режим работы:</p>
			  <p>пн-пт: с 09:00 до 19:00</p>
			  <p>сб-вс: с 10:00 до 18:00</p>
			</li>
			<li>
			  <p><i class="icon-location"></i>Наш адрес:</p>
			  <p>г. Ачинск</p>
			  <p>Дружбы народов, д. 8.</p>
			</li>
		  </ul>
		</div>
		
		<div class="col-md-7">
		  <div class="map">
<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A5ac4daba234571f5205b854d7b7186472327f1ba38d1b1d6a0c7664baeb33ea9&amp;width=640&amp;height=275&amp;lang=ru_RU&amp;scroll=true"></script>			
  </div>
		</div>
	  </div>
	</div>
	</section>

	<footer class="footer">
	  <div class="container">
	  <div class="row">
		<div class="col">
		  <ul class="footer-box">
			<li class="footer-item"><a href="#" class="bottom-logo"><img class="img-responsive" src="images/bottom-logo.png" alt="logo"></a></li>
			<li class="footer-item copy-r">Сервисный центр «Надежда». © 2022 Все права защищены<br><span>ИНН 0000000000, ОГРНИП 0000000000000</span></li>
			  <li class="footer-item">
				<ul>
				  <li class="footer__phone">8-933-333-33-33</li>
				  <li class="socials">
					<a href="https://vk.com/" class="vk-link" target="blank"><i class="icon-vk"></i></a>
					<a href="https://www.youtube.com/" target="blank"><i class="icon-youtube"></i></a>
					<a href="https://www.ok.ru/" target="blank"><i class="icon-odnoklassniki"></i></a>
				  </li>
				</ul>
			  </li>
			  </ul>
			</div>
		</div>
	  </div>
	</footer>

	
	
		<script src="js/jquery-3.2.1.min.js"></script>
	<script src="js/slick.min.js"></script>
	<script src="js/jquery.magnific-popup.min.js"></script>
	<script src="js/inputmask.min.js"></script>
	<script src="js/jquery.inputmask.min.js"></script>
	<script src="js/scripts.js"></script>
	<script src="js/bootstrap.min.js"></script>


<script>
        (function(w,d,u){
                var s=d.createElement('script');s.async=true;s.src=u+'?'+(Date.now()/60000|0);
                var h=d.getElementsByTagName('script')[0];h.parentNode.insertBefore(s,h);
        })(window,document,'https://cdn.bitrix24.ru/b1505153/crm/site_button/loader_16_ty31o9.js');
</script>

<!-- WantResult Pixel -->
<script type="text/javascript">
    (function (d, w) {
        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script");
            s.type = "text/javascript";
            s.async = true;
            s.src = "https://qoopler.ru/index.php?ref="+d.referrer+"&page=" + encodeURIComponent(w.location.href);
            n.parentNode.insertBefore(s, n);
    })(document, window);
</script>
<!-- /WantResult Pixel -->
	


	
  
</body></html>